### ISSUE TITLE
Scrollbar scroll very slowly with Firefox

### ISSUE THREAD

**Issue by guirak** [JPro-one/JPro-tickets#113]
Hi Florian,

I'm preparing a design of a new project and I discovered recently JPro. It seems to me perfect as it will permit me to develop web apps with a technology that I know very well. 
As the choice of technology will have a impact for several years, it's essential for me to know how JPro is mature. 
I am doing several draft to be sure and I encounter some problems. 
1 - When launching on a firefox 78.15.0esr on Debian, the scrollbar of a scrollpane scroll very slowly with the mouse wheel.
2 - When launching on a chome 95.0.4638.69 on Debian, the scrollbar is scrolling well but after manipulating it, the app doesn't react anymore on mouse actions. Clicks, mouse wheel doesn't triggers any action on components.

Maybe there is something that I'm doing bad. 

Here is a screenshot of my app :   
![DraftWebApp](https://user-images.githubusercontent.com/93905646/140704642-dcf48726-5aef-4e54-a582-51821d880c03.png)

And here is the my fxml : 
`
   <BorderPane>
[...]
      <left>
         <ScrollPane BorderPane.alignment="CENTER">
            <content>
               <VBox fx:id="vboxToFill" prefWidth="200.0" />
            </content>
         </ScrollPane>
      </left>
   </BorderPane>
`
I'm adding the buttons to the vbox dynamically to trigger the display oh the scrollbar but I have the same problem when elements are yet present in the fxml.

Thank you for your answer.

**Comment by FlorianKirmaier** [comment]
Hi @guirak ,

#### performance and freeze
I've investigated a bit - and I've noticed one bug which could have caused a perceived bad performance.
On FireFox - when dragging the scrollbar - the events were lost when the mouse was outside the browser.
This is now fixed in the next version.
Another Bug that we've found and fixed recently - could cause that the UI froze after a download. This could explain your second point.
Can you try the version `2021.2.1-SNAPSHOT`. which contains fixes for both issues?
Please give feedback - whether this fixes some of your mentioned issues.

#### mouse wheel
Then you've mentioned, that the MouseWheel scrolls very slow on Debian/Firefox. Do you mean the scroll distance per scroll is unusually low? Or do you mean that it doesn't respond fast enough? If it's the scroll distance, then it might be related to the ScrollEvents created by the OS - which can cause subtle differences.

If the new version doesn't fix the problem, I would suggest you contact us via our contact formula `https://www.jpro.one/contact`, then you can show us the problem directly via screen-sharing. Or you could send us a video with the issue.

Floian Kirmaier

**Comment by guirak** [comment]
Hi Florian, 
Thank you for your answer.
I have just tried on Firefox and Chrome the version 2021.2.1-SNAPSHOT.
- Firefox : the problem is still present. The problem is a scroll distance problem : the scroll with the mouse wheel is done immediately but the scroll distance is very low. The problem occurs only on Firefox. It is not present with Chrome or when launching the app as a classic Java desktop app.
- Chrome : The behavior has changed with the new version :  the problem of absence of response of mouse events has disappeared. Instead, the scroll pane scroll on mouse move until I click on a component outside the scrollpane to change the focus.

Ok, I will try to send you some video with the issues. Can I send you them to the support e-mail adress ? 

Thank you.

**Comment by FlorianKirmaier** [comment]
@guirak 
Yes, you can send the video to `support@jpro.one`.
I think that should clear up what exactly is happening.

**Comment by FlorianKirmaier** [comment]
fixed in 2021.2.1 (which was verified by the reporter on a SNAPSHOT build)
